#!/usr/bin/env python3
from __future__ import annotations

import base64
import datetime as dt
import json
import math
import os
import re
import sqlite3
import subprocess
import sys
import threading
import time
import traceback
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import requests
from requests.cookies import RequestsCookieJar

from PySide6.QtCore import QThread, QTimer, Qt, Signal
from PySide6.QtGui import QColor, QPainter, QPen
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QDoubleSpinBox,
    QFormLayout,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QSpinBox,
    QSplitter,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding

    HAS_CRYPTOGRAPHY = True
except Exception:
    HAS_CRYPTOGRAPHY = False

PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxZ9YwQ1CVM4zNHVNPxoD
Sz6uFGEcyHUOFkoA2hnijjJccCNRGnYlQmnCmaKPtCPiJ26ibXcL9BpfputJpE7Q
cJcJx8CN0Pr/MceYQraFS3UG+zNdI6tGzLDGrBoB+5WFSbK6aOdHFJfcoBfdULHb
g2eGp2IJwSPal3lFNwE/oTL3K1z7EiwbDq0LrY7FcwMGmG3EFaGtMxRy/cq3r0xR
M1V7WIu1I6gw463luLs6NFCdrY/fiXoSrXRf6sOTZClXeRhKjA6c0wLIxizgw6ll
4EeffYVBQSKlEjJJR2y7cxxbp1XkC19evxe0DYbnsemogDcSkmDCj75hsgwuzoTM
FwIDAQAB
-----END PUBLIC KEY-----
"""

TEST_DOMAIN_DEFAULT = "speedtest.selectel.ru"
TEST_URL_DEFAULT = "https://speedtest.selectel.ru/1GB"
BYTES_TARGET_DEFAULT = 8 * 1024 * 1024
TIMEOUT_SECONDS_DEFAULT = 30
IP_STABILIZE_SECONDS_DEFAULT = 1.2

STATE_FILE = "optimizer_state.json"
CONFIG_FILE = "optimizer_config.json"
DB_FILE = "optimizer_stats.db"
COOKIE_FILE = "router_session.cookies"


class ApiError(RuntimeError):
    pass


@dataclass
class TunnelInfo:
    tunnel_code: str
    region_code: str
    country_code: str
    active_num: int
    active_ip: str
    added_by_user: bool


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def as_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except Exception:
        return default


def as_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


class DeeperApiClient:
    def __init__(self, base_url: str, cookie_path: Path):
        self.base_url = base_url.rstrip("/")
        self.cookie_path = cookie_path
        self.session = requests.Session()
        self.session.headers.update(
            {
                "User-Agent": "Mozilla/5.0",
                "Accept": "application/json, text/plain, */*",
                "Content-Type": "application/json",
            }
        )
        self._load_cookies()

    def _load_cookies(self) -> None:
        if not self.cookie_path.exists():
            return
        try:
            text = self.cookie_path.read_text("utf-8", errors="ignore").splitlines()
            jar: RequestsCookieJar = self.session.cookies
            for line in text:
                if not line.strip():
                    continue
                if line.startswith("#HttpOnly_"):
                    line = line[len("#HttpOnly_") :]
                elif line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 7:
                    continue
                domain, path, name, value = parts[0], parts[2], parts[5], parts[6]
                jar.set(name, value, domain=domain, path=path)
        except Exception:
            pass

    def _save_cookies(self) -> None:
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by Deeper Optimizer",
            "",
        ]
        for c in self.session.cookies:
            domain = c.domain or "34.34.34.34"
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.path or "/"
            secure = "TRUE" if c.secure else "FALSE"
            expires = str(int(c.expires or (time.time() + 3600)))
            lines.append("\t".join([domain, flag, path, secure, expires, c.name, c.value]))
        self.cookie_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _encrypt_password(self, password: str) -> str:
        if HAS_CRYPTOGRAPHY:
            key = serialization.load_pem_public_key(PUBLIC_KEY_PEM.encode("utf-8"))
            encrypted = key.encrypt(
                password.encode("utf-8"),
                padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA1()), algorithm=hashes.SHA1(), label=None),
            )
            return base64.b64encode(encrypted).decode("ascii")

        node_script = (
            "const crypto=require('crypto');"
            "const key=process.argv[1];"
            "const pwd=process.argv[2];"
            "process.stdout.write(crypto.publicEncrypt(key,Buffer.from(pwd)).toString('base64'));"
        )
        proc = subprocess.run(["node", "-e", node_script, PUBLIC_KEY_PEM, password], capture_output=True, text=True)
        if proc.returncode != 0:
            raise ApiError("Cannot encrypt password: install cryptography package or node.js")
        return proc.stdout.strip()

    def _url(self, path: str) -> str:
        if path.startswith("http://") or path.startswith("https://"):
            return path
        if not path.startswith("/"):
            path = "/" + path
        return self.base_url + path

    def request(self, method: str, path: str, params: dict[str, Any] | None = None, json_body: Any | None = None) -> Any:
        url = self._url(path)
        resp = self.session.request(method.upper(), url, params=params, json=json_body, timeout=30)
        ctype = (resp.headers.get("Content-Type") or "").lower()
        body: Any
        if "json" in ctype or (resp.text[:1] in "[{"):
            try:
                body = resp.json()
            except Exception:
                body = {"raw": resp.text}
        else:
            body = {"raw": resp.text}
        if resp.status_code >= 400:
            raise ApiError(f"{method.upper()} {path} -> {resp.status_code}: {body}")
        return body

    def login(self, username: str, password: str) -> dict[str, Any]:
        payload = {"username": username, "password": self._encrypt_password(password)}
        data = self.request("POST", "/api/admin/login", json_body=payload)
        self._save_cookies()
        return data

    def validate_token(self) -> dict[str, Any]:
        return self.request("POST", "/api/admin/validateToken")

    def list_tunnels(self) -> list[dict[str, Any]]:
        data = self.request("GET", "/api/smartRoute/listTunnels")
        return data if isinstance(data, list) else []

    def list_tunnel_options(self) -> list[dict[str, Any]]:
        data = self.request("GET", "/api/smartRoute/listTunnelOptions")
        return data if isinstance(data, list) else []

    def get_lb_mode(self) -> dict[str, Any]:
        data = self.request("GET", "/api/smartRoute/nodeLbMode")
        return data if isinstance(data, dict) else {}

    def set_lb_mode(self, mode: str) -> dict[str, Any]:
        data = self.request("POST", "/api/smartRoute/nodeLbMode", json_body={"mode": mode})
        return data if isinstance(data, dict) else {}

    def switch_node(self, tunnel_code: str, current_ip: str) -> dict[str, Any]:
        data = self.request(
            "POST",
            "/api/smartRoute/switchNode",
            json_body={"tunnelCode": tunnel_code, "currentIp": current_ip or "0.0.0.0"},
        )
        return data if isinstance(data, dict) else {}

    def add_tunnel(self, region_code: str, country_code: str) -> dict[str, Any]:
        data = self.request("POST", "/api/smartRoute/addTunnel", json_body={"regionCode": region_code, "countryCode": country_code})
        return data if isinstance(data, dict) else {}

    def delete_tunnels(self, tunnel_codes: list[str]) -> dict[str, Any]:
        data = self.request("POST", "/api/smartRoute/deleteTunnels", json_body=tunnel_codes)
        return data if isinstance(data, dict) else {}

    def get_whitelist_all(self) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        page_no = 1
        page_size = 100
        while True:
            data = self.request(
                "GET",
                "/api/smartRoute/getRoutingWhitelist/domain",
                params={"pageNo": page_no, "pageSize": page_size},
            )
            if not isinstance(data, dict):
                break
            rows = data.get("list") if isinstance(data.get("list"), list) else []
            if not rows:
                break
            out.extend(rows)
            if len(rows) < page_size:
                break
            page_no += 1
        return out

    def add_whitelist(self, domain_name: str, tunnel_code: str) -> dict[str, Any]:
        return self.request("POST", "/api/smartRoute/addToWhitelist/domain", json_body={"domainName": domain_name, "tunnelCode": tunnel_code})

    def edit_whitelist(self, domain_name: str, from_tunnel_code: str, to_tunnel_code: str) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/smartRoute/editWhiteEntry/domain",
            json_body={"domainName": domain_name, "fromTunnelCode": from_tunnel_code, "toTunnelCode": to_tunnel_code},
        )

    def get_dpn_mode(self) -> dict[str, Any]:
        data = self.request("GET", "/api/smartRoute/getDpnMode")
        return data if isinstance(data, dict) else {}

    def set_dpn_mode(self, payload: dict[str, Any]) -> dict[str, Any]:
        data = self.request("POST", "/api/smartRoute/setDpnMode", json_body=payload)
        return data if isinstance(data, dict) else {}

    def get_session_speed(self) -> dict[str, Any]:
        data = self.request("GET", "/api/traffic/session-speed")
        return data if isinstance(data, dict) else {}

    def ensure_test_domain_route(self, domain_name: str, tunnel_code: str) -> None:
        wl = self.get_whitelist_all()
        found = None
        for row in wl:
            if str(row.get("domainName", "")).lower() == domain_name.lower():
                found = row
                break
        if not found:
            self.add_whitelist(domain_name, tunnel_code)
            return
        current = str(found.get("tunnelCode", ""))
        if current != tunnel_code:
            self.edit_whitelist(domain_name, current, tunnel_code)


def measure_download_once(url: str, bytes_target: int, timeout_seconds: int, use_range: bool) -> dict[str, Any]:
    req_url = f"{url}{'&' if '?' in url else '?'}_tm_={int(time.time()*1000)}"
    headers = {"Cache-Control": "no-cache"}
    if use_range:
        headers["Range"] = f"bytes=0-{max(1, bytes_target) - 1}"

    started = time.perf_counter()
    bytes_read = 0
    status = 0
    try:
        with requests.get(req_url, headers=headers, stream=True, timeout=timeout_seconds) as resp:
            status = int(resp.status_code)
            for chunk in resp.iter_content(chunk_size=64 * 1024):
                if not chunk:
                    continue
                bytes_read += len(chunk)
                if bytes_read >= bytes_target:
                    break
    except Exception:
        elapsed_ms = int((time.perf_counter() - started) * 1000)
        return {"ok": False, "status": status, "bytes": 0, "ms": elapsed_ms, "mbps": 0.0, "usedRange": use_range}

    elapsed = max(0.001, time.perf_counter() - started)
    elapsed_ms = int(elapsed * 1000)
    expected_206 = bool(use_range)
    ok = (status == 206 if expected_206 else status in (200, 206)) and bytes_read > 0
    mbps = ((bytes_read * 8.0) / elapsed) / 1e6 if ok else 0.0
    return {
        "ok": ok,
        "status": status,
        "bytes": int(bytes_read),
        "ms": elapsed_ms,
        "mbps": round(mbps, 2),
        "usedRange": bool(use_range),
    }


def measure_download_robust(url: str, bytes_target: int, timeout_seconds: int) -> dict[str, Any]:
    first = measure_download_once(url, bytes_target, timeout_seconds, use_range=True)
    if first.get("ok"):
        return first
    return measure_download_once(url, bytes_target, timeout_seconds, use_range=False)


class StatsStorage:
    def __init__(self, db_path: Path):
        self.db_path = db_path
        self._lock = threading.Lock()
        self._init_db()

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._conn() as conn:
            conn.executescript(
                """
                CREATE TABLE IF NOT EXISTS tunnel_measurements (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts TEXT NOT NULL,
                    tunnel_code TEXT,
                    region_code TEXT,
                    country_code TEXT,
                    ip TEXT,
                    mbps REAL,
                    latency_ms INTEGER,
                    bytes_count INTEGER,
                    status_code INTEGER
                );

                CREATE TABLE IF NOT EXISTS tunnel_snapshots (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts TEXT NOT NULL,
                    source TEXT NOT NULL,
                    payload_json TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS failover_actions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts TEXT NOT NULL,
                    from_tunnel TEXT,
                    to_tunnel TEXT,
                    reason TEXT,
                    status TEXT,
                    detail TEXT
                );
                """
            )

    def save_snapshot(self, source: str, payload: Any) -> None:
        with self._lock, self._conn() as conn:
            conn.execute(
                "INSERT INTO tunnel_snapshots(ts, source, payload_json) VALUES (?, ?, ?)",
                (now_iso(), source, json.dumps(payload, ensure_ascii=False)),
            )

    def save_measurement(self, tunnel: dict[str, Any], row: dict[str, Any]) -> None:
        with self._lock, self._conn() as conn:
            conn.execute(
                """
                INSERT INTO tunnel_measurements(
                    ts, tunnel_code, region_code, country_code, ip, mbps, latency_ms, bytes_count, status_code
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    now_iso(),
                    str(tunnel.get("tunnelCode", "")),
                    str(tunnel.get("regionCode", "")),
                    str(tunnel.get("countryCode", "")),
                    str(row.get("ip", "")),
                    float(row.get("mbps", 0.0)),
                    int(row.get("ms", 0)),
                    int(row.get("bytes", 0)),
                    int(row.get("status", 0)),
                ),
            )

    def save_failover(self, from_tunnel: str, to_tunnel: str, reason: str, status: str, detail: str = "") -> None:
        with self._lock, self._conn() as conn:
            conn.execute(
                "INSERT INTO failover_actions(ts, from_tunnel, to_tunnel, reason, status, detail) VALUES (?, ?, ?, ?, ?, ?)",
                (now_iso(), from_tunnel, to_tunnel, reason, status, detail),
            )

    def get_stats_by_tunnel(self) -> dict[str, dict[str, Any]]:
        with self._lock, self._conn() as conn:
            rows = conn.execute(
                """
                SELECT
                    tunnel_code,
                    MAX(region_code) AS region_code,
                    MAX(country_code) AS country_code,
                    COUNT(*) AS samples,
                    COUNT(DISTINCT ip) AS uniq_ips,
                    AVG(mbps) AS avg_mbps,
                    MAX(mbps) AS max_mbps,
                    MAX(ts) AS last_ts
                FROM tunnel_measurements
                GROUP BY tunnel_code
                """
            ).fetchall()
        out: dict[str, dict[str, Any]] = {}
        for r in rows:
            out[str(r["tunnel_code"])] = {
                "region_code": r["region_code"],
                "country_code": r["country_code"],
                "samples": int(r["samples"] or 0),
                "uniq_ips": int(r["uniq_ips"] or 0),
                "avg_mbps": round(float(r["avg_mbps"] or 0.0), 2),
                "max_mbps": round(float(r["max_mbps"] or 0.0), 2),
                "last_ts": r["last_ts"] or "",
            }
        return out

    def get_speed_series(self, tunnel_code: str, limit: int = 120) -> list[float]:
        with self._lock, self._conn() as conn:
            rows = conn.execute(
                "SELECT mbps FROM tunnel_measurements WHERE tunnel_code=? ORDER BY id DESC LIMIT ?",
                (tunnel_code, int(limit)),
            ).fetchall()
        values = [float(r["mbps"] or 0.0) for r in reversed(rows)]
        return values

    def get_top_candidates(self, limit: int = 20) -> list[dict[str, Any]]:
        with self._lock, self._conn() as conn:
            rows = conn.execute(
                """
                SELECT tunnel_code, MAX(region_code) AS region_code, MAX(country_code) AS country_code,
                       AVG(mbps) AS avg_mbps, MAX(mbps) AS max_mbps, COUNT(*) AS samples
                FROM tunnel_measurements
                GROUP BY tunnel_code
                HAVING COUNT(*) >= 1
                ORDER BY avg_mbps DESC, max_mbps DESC
                LIMIT ?
                """,
                (int(limit),),
            ).fetchall()
        out: list[dict[str, Any]] = []
        for r in rows:
            out.append(
                {
                    "tunnelCode": r["tunnel_code"],
                    "regionCode": r["region_code"],
                    "countryCode": r["country_code"],
                    "avgMbps": round(float(r["avg_mbps"] or 0.0), 2),
                    "maxMbps": round(float(r["max_mbps"] or 0.0), 2),
                    "samples": int(r["samples"] or 0),
                }
            )
        return out

    def get_latest_snapshot(self, source: str) -> Any | None:
        with self._lock, self._conn() as conn:
            row = conn.execute(
                "SELECT payload_json FROM tunnel_snapshots WHERE source=? ORDER BY id DESC LIMIT 1",
                (source,),
            ).fetchone()
        if not row:
            return None
        try:
            return json.loads(row["payload_json"])
        except Exception:
            return None


class SparklineWidget(QWidget):
    def __init__(self, parent: QWidget | None = None):
        super().__init__(parent)
        self._values: list[float] = []
        self.setMinimumHeight(120)

    def set_values(self, values: list[float]) -> None:
        self._values = values[-240:]
        self.update()

    def paintEvent(self, event):  # noqa: N802
        super().paintEvent(event)
        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)

        rect = self.rect().adjusted(6, 6, -6, -6)
        painter.fillRect(rect, QColor("#0b1525"))

        if len(self._values) < 2:
            painter.setPen(QColor("#7d8ba1"))
            painter.drawText(rect.adjusted(8, 8, -8, -8), Qt.AlignCenter, "No speed history")
            return

        vmax = max(self._values)
        vmin = min(self._values)
        if math.isclose(vmax, vmin):
            vmax = vmin + 1.0

        n = len(self._values)
        pts = []
        for i, v in enumerate(self._values):
            x = rect.left() + (i / (n - 1)) * rect.width()
            y = rect.bottom() - ((v - vmin) / (vmax - vmin)) * rect.height()
            pts.append((x, y))

        painter.setPen(QPen(QColor("#25364d"), 1))
        for frac in (0.25, 0.5, 0.75):
            yy = rect.top() + frac * rect.height()
            painter.drawLine(rect.left(), int(yy), rect.right(), int(yy))

        painter.setPen(QPen(QColor("#4db6ff"), 2))
        for i in range(1, len(pts)):
            painter.drawLine(int(pts[i - 1][0]), int(pts[i - 1][1]), int(pts[i][0]), int(pts[i][1]))

        painter.setPen(QColor("#c6d4e3"))
        painter.drawText(rect.adjusted(8, 8, -8, -8), Qt.AlignTop | Qt.AlignLeft, f"min {vmin:.2f} Mbps")
        painter.drawText(rect.adjusted(8, 8, -8, -8), Qt.AlignTop | Qt.AlignRight, f"max {vmax:.2f} Mbps")


class StatCard(QFrame):
    def __init__(self, title: str, parent: QWidget | None = None):
        super().__init__(parent)
        self.setObjectName("statCard")
        lay = QVBoxLayout(self)
        self.title = QLabel(title)
        self.title.setObjectName("cardTitle")
        self.value = QLabel("-")
        self.value.setObjectName("cardValue")
        lay.addWidget(self.title)
        lay.addWidget(self.value)

    def set_value(self, text: str) -> None:
        self.value.setText(text)


class ScanWorker(QThread):
    progress = Signal(str)
    tunnel_done = Signal(dict, list, dict)
    done = Signal(dict)
    failed = Signal(str)

    def __init__(
        self,
        base_url: str,
        cookie_path: Path,
        tunnels: list[dict[str, Any]],
        test_domain: str,
        test_url: str,
        bytes_target: int,
        timeout_seconds: int,
        ip_stabilize_seconds: float,
    ):
        super().__init__()
        self.base_url = base_url
        self.cookie_path = cookie_path
        self.tunnels = tunnels
        self.test_domain = test_domain
        self.test_url = test_url
        self.bytes_target = bytes_target
        self.timeout_seconds = timeout_seconds
        self.ip_stabilize_seconds = ip_stabilize_seconds
        self._stop_event = threading.Event()

    def stop(self) -> None:
        self._stop_event.set()

    def _stopped(self) -> bool:
        return self._stop_event.is_set()

    def run(self):  # noqa: D401
        api = DeeperApiClient(self.base_url, self.cookie_path)
        all_rows: list[dict[str, Any]] = []
        try:
            for idx, t in enumerate(self.tunnels, start=1):
                if self._stopped():
                    break

                tunnel_code = str(t.get("tunnelCode", ""))
                self.progress.emit(f"[{idx}/{len(self.tunnels)}] Scanning {tunnel_code} ...")
                summary, rows = self.scan_tunnel_all_ips(api, t)
                self.tunnel_done.emit(t, rows, summary)
                all_rows.append({"tunnel": t, "summary": summary, "rows": rows})

            self.done.emit({"count": len(all_rows), "results": all_rows, "stopped": self._stopped()})
        except Exception as exc:
            self.failed.emit(f"Scan failed: {exc}\n{traceback.format_exc()}")

    def scan_tunnel_all_ips(self, api: DeeperApiClient, tunnel: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
        per_ip: list[dict[str, Any]] = []
        prev_mode = None
        total = max(0, as_int(tunnel.get("activeNum"), 0))
        tunnel_code = str(tunnel.get("tunnelCode", ""))

        if total <= 0:
            return {"sumMbps": 0.0, "ipCount": 0, "loops": 0}, per_ip

        try:
            mode_data = api.get_lb_mode()
            prev_mode = str(mode_data.get("mode") or "")
            if prev_mode and prev_mode != "none":
                api.set_lb_mode("none")

            api.ensure_test_domain_route(self.test_domain, tunnel_code)

            seen: set[str] = set()
            current_ip = str(tunnel.get("activeIp") or "")
            max_loops = max(12, total * 6 + 12)
            guard = 0

            while len(seen) < total and guard < max_loops:
                if self._stopped():
                    break

                guard += 1
                if not current_ip or current_ip in seen:
                    sw = api.switch_node(tunnel_code, current_ip or "0.0.0.0")
                    current_ip = str(sw.get("activeIp") or "")
                    time.sleep(self.ip_stabilize_seconds)
                    continue

                time.sleep(self.ip_stabilize_seconds)
                r = measure_download_robust(self.test_url, self.bytes_target, self.timeout_seconds)
                row = {
                    "ip": current_ip,
                    "mbps": round(as_float(r.get("mbps"), 0.0), 2),
                    "ms": as_int(r.get("ms"), 0),
                    "bytes": as_int(r.get("bytes"), 0),
                    "status": as_int(r.get("status"), 0),
                    "usedRange": bool(r.get("usedRange")),
                }
                per_ip.append(row)
                sw = api.switch_node(tunnel_code, current_ip)
                seen.add(current_ip)
                current_ip = str(sw.get("activeIp") or "")

            sum_mbps = round(sum(as_float(p.get("mbps"), 0.0) for p in per_ip), 2)
            return {"sumMbps": sum_mbps, "ipCount": len(per_ip), "loops": guard}, per_ip
        finally:
            try:
                if prev_mode and prev_mode != "none":
                    api.set_lb_mode(prev_mode)
            except Exception:
                pass


class FailoverWorker(QThread):
    done = Signal(dict)
    failed = Signal(str)

    def __init__(self, base_url: str, cookie_path: Path, db_path: Path, auto_apply: bool = True):
        super().__init__()
        self.base_url = base_url
        self.cookie_path = cookie_path
        self.db_path = db_path
        self.auto_apply = auto_apply

    def run(self):
        api = DeeperApiClient(self.base_url, self.cookie_path)
        store = StatsStorage(self.db_path)
        try:
            mode = api.get_dpn_mode()
            tunnels = api.list_tunnels()
            tmap = {str(t.get("tunnelCode", "")): t for t in tunnels}

            dpn_mode = str(mode.get("dpnMode") or "")
            if dpn_mode == "smart":
                current = str(mode.get("smartTunnel") or mode.get("tunnelCode") or "")
            else:
                current = str(mode.get("fullTunnel") or mode.get("tunnelCode") or "")

            current_tunnel = tmap.get(current)
            healthy = bool(current_tunnel and as_int(current_tunnel.get("activeNum"), 0) > 0)

            if healthy:
                self.done.emit({"status": "ok", "current": current, "reason": "active tunnel healthy", "switched": False})
                return

            ranking = store.get_top_candidates(limit=20)
            candidate = None
            for r in ranking:
                code = str(r.get("tunnelCode", ""))
                if code == current:
                    continue
                t = tmap.get(code)
                if t and as_int(t.get("activeNum"), 0) > 0:
                    candidate = t
                    break

            if candidate is None:
                snapshot = store.get_latest_snapshot("list_tunnels")
                if isinstance(snapshot, list):
                    for row in snapshot:
                        rc = str(row.get("regionCode") or "")
                        cc = str(row.get("countryCode") or "")
                        code = str(row.get("tunnelCode") or "")
                        if not (rc and cc):
                            continue
                        try:
                            api.add_tunnel(rc, cc)
                            time.sleep(0.4)
                        except Exception:
                            continue
                        tunnels = api.list_tunnels()
                        tmap = {str(t.get("tunnelCode", "")): t for t in tunnels}
                        if code in tmap and as_int(tmap[code].get("activeNum"), 0) > 0:
                            candidate = tmap[code]
                            break

            if not candidate:
                self.done.emit(
                    {
                        "status": "no_backup",
                        "current": current,
                        "reason": "no healthy backup tunnel in cache/snapshot",
                        "switched": False,
                    }
                )
                return

            if not self.auto_apply:
                self.done.emit(
                    {
                        "status": "candidate",
                        "current": current,
                        "candidate": candidate.get("tunnelCode"),
                        "reason": "current unhealthy",
                        "switched": False,
                    }
                )
                return

            target_code = str(candidate.get("tunnelCode") or "")
            new_mode = dict(mode)
            if dpn_mode == "smart":
                new_mode["smartTunnel"] = target_code
            else:
                new_mode["dpnMode"] = "full"
                new_mode["fullTunnel"] = target_code
                new_mode["tunnelCode"] = target_code

            api.set_dpn_mode(new_mode)
            current_ip = str(candidate.get("activeIp") or "0.0.0.0")
            try:
                api.switch_node(target_code, current_ip)
            except Exception:
                pass

            self.done.emit(
                {
                    "status": "switched",
                    "current": current,
                    "candidate": target_code,
                    "reason": "current unhealthy",
                    "switched": True,
                }
            )
        except Exception as exc:
            self.failed.emit(f"Failover check failed: {exc}\n{traceback.format_exc()}")


def redact_text(text: str) -> str:
    text = re.sub(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", "<IP_REDACTED>", text)
    text = re.sub(r"Deeper-[A-Za-z0-9\-_|]+", "<DEVICE_ID_REDACTED>", text)
    text = re.sub(r"eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}", "<TOKEN_REDACTED>", text)
    return text


def redact_json(value: Any) -> Any:
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            if str(k).lower() in {"cookie", "token", "authorization", "password", "deviceid"}:
                out[k] = "<REDACTED>"
            else:
                out[k] = redact_json(v)
        return out
    if isinstance(value, list):
        return [redact_json(v) for v in value]
    if isinstance(value, str):
        return redact_text(value)
    return value


def build_public_api_archive(base_dir: Path) -> Path:
    public_dir = base_dir / "public_docs"
    if public_dir.exists():
        for p in sorted(public_dir.rglob("*"), reverse=True):
            if p.is_file():
                p.unlink()
            elif p.is_dir():
                try:
                    p.rmdir()
                except OSError:
                    pass
    public_dir.mkdir(parents=True, exist_ok=True)

    source_files = [
        "ROUTER_API_FULL.md",
        "router_api_catalog.json",
        "router_api_openapi_like.json",
        "README.md",
    ]

    for name in source_files:
        src = base_dir / name
        if not src.exists():
            continue
        dst_name = name.replace(".md", "_PUBLIC.md").replace(".json", "_PUBLIC.json")
        dst = public_dir / dst_name
        if src.suffix.lower() == ".json":
            try:
                data = json.loads(src.read_text("utf-8"))
                dst.write_text(json.dumps(redact_json(data), ensure_ascii=False, indent=2), encoding="utf-8")
            except Exception:
                dst.write_text(redact_text(src.read_text("utf-8", errors="ignore")), encoding="utf-8")
        else:
            dst.write_text(redact_text(src.read_text("utf-8", errors="ignore")), encoding="utf-8")

    readme = public_dir / "README_PUBLIC.txt"
    readme.write_text(
        "Public API docs archive generated by Deeper Optimizer.\n"
        "Sensitive values (IP/device/token/password-like strings) are redacted.\n"
        "No session cookies or local measurement databases are included.\n",
        encoding="utf-8",
    )

    zip_path = base_dir / "deeper_api_docs_public.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(public_dir.rglob("*")):
            if p.is_file():
                zf.write(p, arcname=p.relative_to(public_dir))
    return zip_path


class MainWindow(QMainWindow):
    def __init__(self, base_dir: Path):
        super().__init__()
        self.base_dir = base_dir
        self.config_path = base_dir / CONFIG_FILE
        self.state_path = base_dir / STATE_FILE
        self.db_path = base_dir / DB_FILE
        self.cookie_path = base_dir / COOKIE_FILE

        self.store = StatsStorage(self.db_path)
        self.client = DeeperApiClient("http://34.34.34.34", self.cookie_path)

        self.scan_worker: ScanWorker | None = None
        self.failover_worker: FailoverWorker | None = None
        self.monitor_timer = QTimer(self)
        self.monitor_timer.timeout.connect(self.run_failover_check)

        self.latest_tunnels: list[dict[str, Any]] = []

        self.setWindowTitle("Deeper Tunnel Optimizer")
        self.resize(1580, 980)
        self._build_ui()
        self._apply_style()
        self.load_config()
        self.refresh_tunnels(silent=True)

        self.traffic_timer = QTimer(self)
        self.traffic_timer.timeout.connect(self.poll_traffic)
        self.traffic_timer.start(3000)

    def _build_ui(self):
        root = QWidget()
        self.setCentralWidget(root)
        v = QVBoxLayout(root)

        conn_box = QGroupBox("Connection")
        conn_form = QFormLayout(conn_box)
        self.base_url_edit = QLineEdit("http://34.34.34.34")
        self.username_edit = QLineEdit("admin")
        self.password_edit = QLineEdit("admin")
        self.password_edit.setEchoMode(QLineEdit.Password)
        conn_form.addRow("Base URL", self.base_url_edit)
        conn_form.addRow("Username", self.username_edit)
        conn_form.addRow("Password", self.password_edit)

        settings_box = QGroupBox("Scan settings")
        settings_form = QFormLayout(settings_box)
        self.test_domain_edit = QLineEdit(TEST_DOMAIN_DEFAULT)
        self.test_url_edit = QLineEdit(TEST_URL_DEFAULT)
        self.bytes_target_spin = QSpinBox()
        self.bytes_target_spin.setRange(1, 1024)
        self.bytes_target_spin.setValue(BYTES_TARGET_DEFAULT // (1024 * 1024))
        self.timeout_spin = QSpinBox()
        self.timeout_spin.setRange(3, 120)
        self.timeout_spin.setValue(TIMEOUT_SECONDS_DEFAULT)
        self.ip_stabilize_spin = QDoubleSpinBox()
        self.ip_stabilize_spin.setRange(0.2, 10.0)
        self.ip_stabilize_spin.setSingleStep(0.1)
        self.ip_stabilize_spin.setValue(IP_STABILIZE_SECONDS_DEFAULT)
        self.route_domain_check = QCheckBox("Route test domain via tunnel before measurement")
        self.route_domain_check.setChecked(True)
        settings_form.addRow("Test domain", self.test_domain_edit)
        settings_form.addRow("Test URL", self.test_url_edit)
        settings_form.addRow("Bytes target (MB)", self.bytes_target_spin)
        settings_form.addRow("Timeout (sec)", self.timeout_spin)
        settings_form.addRow("IP stabilize (sec)", self.ip_stabilize_spin)
        settings_form.addRow("", self.route_domain_check)

        top = QHBoxLayout()
        top.addWidget(conn_box, 1)
        top.addWidget(settings_box, 2)
        v.addLayout(top)

        buttons = QHBoxLayout()
        self.login_btn = QPushButton("Login")
        self.refresh_btn = QPushButton("Refresh tunnels")
        self.scan_sel_btn = QPushButton("Scan selected")
        self.scan_all_btn = QPushButton("Scan all")
        self.stop_scan_btn = QPushButton("Stop scan")
        self.switch_btn = QPushButton("Switch to selected")
        self.save_snapshot_btn = QPushButton("Save tunnel snapshot")
        self.export_zip_btn = QPushButton("Export PUBLIC API zip")
        self.monitor_btn = QPushButton("Start failover monitor")
        self.monitor_interval_spin = QSpinBox()
        self.monitor_interval_spin.setRange(5, 600)
        self.monitor_interval_spin.setValue(20)
        self.monitor_interval_spin.setPrefix("monitor ")
        self.monitor_interval_spin.setSuffix(" s")

        for btn in [
            self.login_btn,
            self.refresh_btn,
            self.scan_sel_btn,
            self.scan_all_btn,
            self.stop_scan_btn,
            self.switch_btn,
            self.save_snapshot_btn,
            self.export_zip_btn,
            self.monitor_btn,
        ]:
            buttons.addWidget(btn)
        buttons.addWidget(self.monitor_interval_spin)
        v.addLayout(buttons)

        cards_layout = QGridLayout()
        self.card_total = StatCard("Total tunnels")
        self.card_alive = StatCard("Alive (activeNum>0)")
        self.card_measured = StatCard("Measured tunnels")
        self.card_best = StatCard("Best avg Mbps")
        cards_layout.addWidget(self.card_total, 0, 0)
        cards_layout.addWidget(self.card_alive, 0, 1)
        cards_layout.addWidget(self.card_measured, 0, 2)
        cards_layout.addWidget(self.card_best, 0, 3)
        v.addLayout(cards_layout)

        splitter = QSplitter(Qt.Horizontal)

        left = QWidget()
        left_lay = QVBoxLayout(left)
        self.table = QTableWidget(0, 10)
        self.table.setHorizontalHeaderLabels(
            [
                "Tunnel",
                "Region",
                "Country",
                "ActiveNum",
                "ActiveIP",
                "Avg Mbps",
                "Best Mbps",
                "Samples",
                "Unique IPs",
                "Last seen",
            ]
        )
        self.table.setSelectionBehavior(QTableWidget.SelectRows)
        self.table.setSelectionMode(QTableWidget.ExtendedSelection)
        self.table.itemSelectionChanged.connect(self.on_table_selection_changed)
        self.table.verticalHeader().setVisible(False)
        left_lay.addWidget(self.table)

        right = QWidget()
        right_lay = QVBoxLayout(right)
        right_lay.addWidget(QLabel("Tunnel speed history"))
        self.spark = SparklineWidget()
        right_lay.addWidget(self.spark)
        right_lay.addWidget(QLabel("Live traffic (max speed series)"))
        self.traffic_spark = SparklineWidget()
        right_lay.addWidget(self.traffic_spark)
        right_lay.addWidget(QLabel("Log"))
        self.log_edit = QTextEdit()
        self.log_edit.setReadOnly(True)
        right_lay.addWidget(self.log_edit, 1)

        splitter.addWidget(left)
        splitter.addWidget(right)
        splitter.setSizes([1100, 450])
        v.addWidget(splitter, 1)

        self.login_btn.clicked.connect(self.login)
        self.refresh_btn.clicked.connect(self.refresh_tunnels)
        self.scan_sel_btn.clicked.connect(self.scan_selected)
        self.scan_all_btn.clicked.connect(self.scan_all)
        self.stop_scan_btn.clicked.connect(self.stop_scan)
        self.switch_btn.clicked.connect(self.switch_to_selected)
        self.save_snapshot_btn.clicked.connect(self.save_snapshot)
        self.export_zip_btn.clicked.connect(self.export_public_zip)
        self.monitor_btn.clicked.connect(self.toggle_monitor)

    def _apply_style(self):
        self.setStyleSheet(
            """
            QWidget {
                background: #050b17;
                color: #d2ddee;
                font-family: Segoe UI, Arial, sans-serif;
                font-size: 12px;
            }
            QGroupBox {
                border: 1px solid #26354f;
                border-radius: 8px;
                margin-top: 8px;
                padding: 8px;
                font-weight: 600;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 8px;
                padding: 0 4px;
                color: #9ec7ff;
            }
            QLineEdit, QSpinBox, QDoubleSpinBox, QTextEdit, QTableWidget {
                background: #0b1525;
                border: 1px solid #243551;
                border-radius: 6px;
                padding: 4px;
                selection-background-color: #14304f;
            }
            QPushButton {
                background: #102844;
                border: 1px solid #295080;
                border-radius: 6px;
                padding: 6px 10px;
                color: #e8f2ff;
                font-weight: 600;
            }
            QPushButton:hover {
                background: #153a63;
            }
            QPushButton:pressed {
                background: #0d233b;
            }
            #statCard {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0b1525, stop:1 #0f2038);
                border: 1px solid #27446a;
                border-radius: 8px;
                padding: 8px;
            }
            #cardTitle { color: #8bb7f0; font-size: 11px; }
            #cardValue { color: #f4fbff; font-size: 18px; font-weight: 700; }
            QHeaderView::section {
                background: #102039;
                color: #b9d3f1;
                border: 0;
                border-right: 1px solid #1d3350;
                padding: 6px;
                font-weight: 700;
            }
            """
        )

    def load_config(self):
        cfg = {}
        if self.config_path.exists():
            try:
                cfg = json.loads(self.config_path.read_text("utf-8"))
            except Exception:
                cfg = {}
        self.base_url_edit.setText(str(cfg.get("base_url") or self.base_url_edit.text()))
        self.username_edit.setText(str(cfg.get("username") or self.username_edit.text()))
        self.test_domain_edit.setText(str(cfg.get("test_domain") or self.test_domain_edit.text()))
        self.test_url_edit.setText(str(cfg.get("test_url") or self.test_url_edit.text()))
        if cfg.get("bytes_mb"):
            self.bytes_target_spin.setValue(int(cfg["bytes_mb"]))
        if cfg.get("timeout"):
            self.timeout_spin.setValue(int(cfg["timeout"]))
        if cfg.get("ip_stabilize"):
            self.ip_stabilize_spin.setValue(float(cfg["ip_stabilize"]))
        if cfg.get("monitor_interval"):
            self.monitor_interval_spin.setValue(int(cfg["monitor_interval"]))

    def save_config(self):
        cfg = {
            "base_url": self.base_url_edit.text().strip(),
            "username": self.username_edit.text().strip(),
            "test_domain": self.test_domain_edit.text().strip(),
            "test_url": self.test_url_edit.text().strip(),
            "bytes_mb": int(self.bytes_target_spin.value()),
            "timeout": int(self.timeout_spin.value()),
            "ip_stabilize": float(self.ip_stabilize_spin.value()),
            "monitor_interval": int(self.monitor_interval_spin.value()),
        }
        self.config_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2), encoding="utf-8")

    def log(self, msg: str):
        stamp = dt.datetime.now().strftime("%H:%M:%S")
        self.log_edit.append(f"[{stamp}] {msg}")

    def current_client(self) -> DeeperApiClient:
        client = DeeperApiClient(self.base_url_edit.text().strip(), self.cookie_path)
        return client

    def login(self):
        self.save_config()
        try:
            client = self.current_client()
            out = client.login(self.username_edit.text().strip(), self.password_edit.text())
            check = client.validate_token()
            self.client = client
            self.log(f"Login: {out}; validateToken: {check}")
            self.refresh_tunnels(silent=True)
            QMessageBox.information(self, "Login", "Login successful")
        except Exception as exc:
            self.log(f"Login failed: {exc}")
            QMessageBox.critical(self, "Login error", str(exc))

    def refresh_tunnels(self, silent: bool = False):
        try:
            self.save_config()
            self.client = self.current_client()
            tunnels = self.client.list_tunnels()
            self.latest_tunnels = tunnels
            self.store.save_snapshot("list_tunnels", tunnels)
            self.update_table()
            if not silent:
                self.log(f"Tunnels refreshed: {len(tunnels)}")
        except Exception as exc:
            self.log(f"Refresh failed: {exc}")
            if not silent:
                QMessageBox.warning(self, "Refresh failed", str(exc))

    def update_table(self):
        stats = self.store.get_stats_by_tunnel()
        rows = list(self.latest_tunnels)
        rows.sort(key=lambda t: (-(as_int(t.get("activeNum"), 0)), str(t.get("countryCode") or "")))

        self.table.setRowCount(len(rows))
        alive = 0
        for r, t in enumerate(rows):
            code = str(t.get("tunnelCode") or "")
            st = stats.get(code, {})
            if as_int(t.get("activeNum"), 0) > 0:
                alive += 1

            vals = [
                code,
                str(t.get("regionCode") or ""),
                str(t.get("countryCode") or ""),
                str(as_int(t.get("activeNum"), 0)),
                str(t.get("activeIp") or ""),
                f"{as_float(st.get('avg_mbps', 0.0)):.2f}",
                f"{as_float(st.get('max_mbps', 0.0)):.2f}",
                str(as_int(st.get("samples"), 0)),
                str(as_int(st.get("uniq_ips"), 0)),
                str(st.get("last_ts") or ""),
            ]
            for c, v in enumerate(vals):
                item = QTableWidgetItem(v)
                item.setData(Qt.UserRole, t)
                self.table.setItem(r, c, item)

        self.table.resizeColumnsToContents()

        top = self.store.get_top_candidates(limit=1)
        best = f"{top[0]['tunnelCode']} ({top[0]['avgMbps']:.2f})" if top else "-"
        measured = len(stats)
        self.card_total.set_value(str(len(rows)))
        self.card_alive.set_value(str(alive))
        self.card_measured.set_value(str(measured))
        self.card_best.set_value(best)

    def selected_tunnels(self) -> list[dict[str, Any]]:
        selected = self.table.selectionModel().selectedRows() if self.table.selectionModel() else []
        tunnels: list[dict[str, Any]] = []
        for idx in selected:
            item = self.table.item(idx.row(), 0)
            if not item:
                continue
            t = item.data(Qt.UserRole)
            if isinstance(t, dict):
                tunnels.append(t)
        return tunnels

    def scan_selected(self):
        tunnels = self.selected_tunnels()
        if not tunnels:
            QMessageBox.information(self, "Scan", "Select at least one tunnel row")
            return
        self.start_scan(tunnels)

    def scan_all(self):
        if not self.latest_tunnels:
            self.refresh_tunnels(silent=True)
        if not self.latest_tunnels:
            QMessageBox.warning(self, "Scan", "No tunnels available")
            return
        self.start_scan(self.latest_tunnels)

    def start_scan(self, tunnels: list[dict[str, Any]]):
        if self.scan_worker and self.scan_worker.isRunning():
            QMessageBox.information(self, "Scan", "Scan already running")
            return

        self.save_config()
        self.scan_worker = ScanWorker(
            base_url=self.base_url_edit.text().strip(),
            cookie_path=self.cookie_path,
            tunnels=tunnels,
            test_domain=self.test_domain_edit.text().strip(),
            test_url=self.test_url_edit.text().strip(),
            bytes_target=int(self.bytes_target_spin.value()) * 1024 * 1024,
            timeout_seconds=int(self.timeout_spin.value()),
            ip_stabilize_seconds=float(self.ip_stabilize_spin.value()),
        )
        self.scan_worker.progress.connect(self.log)
        self.scan_worker.tunnel_done.connect(self.on_tunnel_done)
        self.scan_worker.done.connect(self.on_scan_done)
        self.scan_worker.failed.connect(self.on_scan_failed)
        self.scan_worker.start()
        self.log(f"Scan started: {len(tunnels)} tunnel(s)")

    def stop_scan(self):
        if self.scan_worker and self.scan_worker.isRunning():
            self.scan_worker.stop()
            self.log("Stop requested for scan worker")

    def on_tunnel_done(self, tunnel: dict[str, Any], per_ip: list[dict[str, Any]], summary: dict[str, Any]):
        for row in per_ip:
            self.store.save_measurement(tunnel, row)
        self.log(
            f"Done {tunnel.get('tunnelCode')} {tunnel.get('regionCode')}/{tunnel.get('countryCode')}"
            f" ips={summary.get('ipCount')} sum={summary.get('sumMbps')} Mbps"
        )
        self.update_table()

    def on_scan_done(self, payload: dict[str, Any]):
        self.log(f"Scan finished. processed={payload.get('count')} stopped={payload.get('stopped')}")
        self.refresh_tunnels(silent=True)

    def on_scan_failed(self, message: str):
        self.log(message)
        QMessageBox.critical(self, "Scan failed", message)

    def on_table_selection_changed(self):
        tunnels = self.selected_tunnels()
        if len(tunnels) != 1:
            return
        code = str(tunnels[0].get("tunnelCode") or "")
        values = self.store.get_speed_series(code)
        self.spark.set_values(values)

    def switch_to_selected(self):
        tunnels = self.selected_tunnels()
        if len(tunnels) != 1:
            QMessageBox.information(self, "Switch", "Select exactly one tunnel")
            return
        target = str(tunnels[0].get("tunnelCode") or "")
        if not target:
            return

        try:
            self.client = self.current_client()
            mode = self.client.get_dpn_mode()
            dpn_mode = str(mode.get("dpnMode") or "")
            payload = dict(mode)
            if dpn_mode == "smart":
                payload["smartTunnel"] = target
            else:
                payload["dpnMode"] = "full"
                payload["fullTunnel"] = target
                payload["tunnelCode"] = target

            self.client.set_dpn_mode(payload)
            active_ip = str(tunnels[0].get("activeIp") or "0.0.0.0")
            try:
                self.client.switch_node(target, active_ip)
            except Exception:
                pass
            self.log(f"Switched active tunnel to {target}")
            self.store.save_failover("manual", target, "manual switch", "ok")
            self.refresh_tunnels(silent=True)
        except Exception as exc:
            self.log(f"Switch failed: {exc}")
            QMessageBox.warning(self, "Switch failed", str(exc))

    def save_snapshot(self):
        try:
            tunnels = self.client.list_tunnels()
            self.store.save_snapshot("manual_snapshot", tunnels)
            self.log(f"Manual snapshot saved with {len(tunnels)} tunnels")
            QMessageBox.information(self, "Snapshot", "Snapshot saved")
        except Exception as exc:
            self.log(f"Snapshot save failed: {exc}")
            QMessageBox.warning(self, "Snapshot", str(exc))

    def toggle_monitor(self):
        if self.monitor_timer.isActive():
            self.monitor_timer.stop()
            self.monitor_btn.setText("Start failover monitor")
            self.log("Failover monitor stopped")
            return
        interval_ms = int(self.monitor_interval_spin.value()) * 1000
        self.monitor_timer.start(interval_ms)
        self.monitor_btn.setText("Stop failover monitor")
        self.log(f"Failover monitor started ({self.monitor_interval_spin.value()}s)")
        self.run_failover_check()

    def run_failover_check(self):
        if self.failover_worker and self.failover_worker.isRunning():
            return
        self.failover_worker = FailoverWorker(
            base_url=self.base_url_edit.text().strip(),
            cookie_path=self.cookie_path,
            db_path=self.db_path,
            auto_apply=True,
        )
        self.failover_worker.done.connect(self.on_failover_done)
        self.failover_worker.failed.connect(self.on_failover_failed)
        self.failover_worker.start()

    def on_failover_done(self, payload: dict[str, Any]):
        status = payload.get("status")
        current = payload.get("current")
        candidate = payload.get("candidate")
        reason = payload.get("reason")

        if status == "switched":
            self.log(f"Failover switched: {current} -> {candidate}; reason={reason}")
            self.store.save_failover(str(current), str(candidate), str(reason), "switched")
            self.refresh_tunnels(silent=True)
        elif status == "ok":
            self.log(f"Failover check: OK ({current})")
        elif status == "candidate":
            self.log(f"Failover candidate: {candidate} (current={current})")
        else:
            self.log(f"Failover check: {status} reason={reason}")
            self.store.save_failover(str(current), str(candidate or ""), str(reason), str(status))

    def on_failover_failed(self, message: str):
        self.log(message)

    def poll_traffic(self):
        try:
            data = self.current_client().get_session_speed()
            traffic = data.get("traffic") if isinstance(data, dict) else None
            if not isinstance(traffic, list):
                return
            values: list[float] = []
            for row in traffic:
                speeds = row.get("speed")
                if isinstance(speeds, list):
                    values.extend([as_float(x, 0.0) for x in speeds[-20:]])
            if values:
                self.traffic_spark.set_values(values[-240:])
        except Exception:
            return

    def export_public_zip(self):
        try:
            zip_path = build_public_api_archive(self.base_dir)
            self.log(f"Public API docs zip created: {zip_path}")
            QMessageBox.information(self, "Archive", f"Created: {zip_path}")
        except Exception as exc:
            self.log(f"Archive export failed: {exc}")
            QMessageBox.warning(self, "Archive", str(exc))

    def closeEvent(self, event):  # noqa: N802
        self.save_config()
        if self.scan_worker and self.scan_worker.isRunning():
            self.scan_worker.stop()
            self.scan_worker.wait(1000)
        super().closeEvent(event)


def ensure_docs_exist(base_dir: Path) -> None:
    readme = base_dir / "README.md"
    if readme.exists():
        return
    readme.write_text(
        "Deeper optimizer UI folder.\n"
        "Run: python deeper_optimizer_ui/deeper_optimizer.py\n",
        encoding="utf-8",
    )


def main():
    this_file = Path(__file__).resolve()
    base_dir = this_file.parent.parent
    ensure_docs_exist(base_dir)

    app = QApplication(sys.argv)
    win = MainWindow(base_dir=base_dir)
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
